export const countries = [
  { name: 'Afghanistan', code: 'AFG', dialCode: '+93' },
  { name: 'Albania', code: 'ALB', dialCode: '+355' },
  { name: 'Algeria', code: 'DZA', dialCode: '+213' },
  { name: 'Andorra', code: 'AND', dialCode: '+376' },
  { name: 'Angola', code: 'AGO', dialCode: '+244' },
  { name: 'Antigua and Barbuda', code: 'ATG', dialCode: '+1-268' },
  { name: 'Argentina', code: 'ARG', dialCode: '+54' },
  { name: 'Armenia', code: 'ARM', dialCode: '+374' },
  { name: 'Australia', code: 'AUS', dialCode: '+61' },
  { name: 'Austria', code: 'AUT', dialCode: '+43' },
  { name: 'Azerbaijan', code: 'AZE', dialCode: '+994' },
  { name: 'Bahamas', code: 'BHS', dialCode: '+1-242' },
  { name: 'Bahrain', code: 'BHR', dialCode: '+973' },
  { name: 'Bangladesh', code: 'BGD', dialCode: '+880' },
  { name: 'Barbados', code: 'BRB', dialCode: '+1-246' },
  { name: 'Belarus', code: 'BLR', dialCode: '+375' },
  { name: 'Belgium', code: 'BEL', dialCode: '+32' },
  { name: 'Belize', code: 'BLZ', dialCode: '+501' },
  { name: 'Benin', code: 'BEN', dialCode: '+229' },
  { name: 'Bhutan', code: 'BTN', dialCode: '+975' },
  { name: 'Bolivia', code: 'BOL', dialCode: '+591' },
  { name: 'Bosnia and Herzegovina', code: 'BIH', dialCode: '+387' },
  { name: 'Botswana', code: 'BWA', dialCode: '+267' },
  { name: 'Brazil', code: 'BRA', dialCode: '+55' },
  { name: 'Brunei', code: 'BRN', dialCode: '+673' },
  { name: 'Bulgaria', code: 'BGR', dialCode: '+359' },
  { name: 'Burkina Faso', code: 'BFA', dialCode: '+226' },
  { name: 'Burundi', code: 'BDI', dialCode: '+257' },
  { name: 'Cabo Verde', code: 'CPV', dialCode: '+238' },
  { name: 'Cambodia', code: 'KHM', dialCode: '+855' },
  { name: 'Cameroon', code: 'CMR', dialCode: '+237' },
  { name: 'Canada', code: 'CAN', dialCode: '+1' },
  { name: 'Central African Republic', code: 'CAF', dialCode: '+236' },
  { name: 'Chad', code: 'TCD', dialCode: '+235' },
  { name: 'Chile', code: 'CHL', dialCode: '+56' },
  { name: 'China', code: 'CHN', dialCode: '+86' },
  { name: 'Colombia', code: 'COL', dialCode: '+57' },
  { name: 'Comoros', code: 'COM', dialCode: '+269' },
  { name: 'Congo', code: 'COG', dialCode: '+242' },
  { name: 'Costa Rica', code: 'CRI', dialCode: '+506' },
  { name: 'Croatia', code: 'HRV', dialCode: '+385' },
  { name: 'Cuba', code: 'CUB', dialCode: '+53' },
  { name: 'Cyprus', code: 'CYP', dialCode: '+357' },
  { name: 'Czech Republic', code: 'CZE', dialCode: '+420' },
  { name: 'Denmark', code: 'DNK', dialCode: '+45' },
  { name: 'Djibouti', code: 'DJI', dialCode: '+253' },
  { name: 'Dominica', code: 'DMA', dialCode: '+1-767' },
  { name: 'Dominican Republic', code: 'DOM', dialCode: '+1-809' },
  { name: 'Ecuador', code: 'ECU', dialCode: '+593' },
  { name: 'Egypt', code: 'EGY', dialCode: '+20' },
  { name: 'El Salvador', code: 'SLV', dialCode: '+503' },
  { name: 'Equatorial Guinea', code: 'GNQ', dialCode: '+240' },
  { name: 'Eritrea', code: 'ERI', dialCode: '+291' },
  { name: 'Estonia', code: 'EST', dialCode: '+372' },
  { name: 'Eswatini', code: 'SWZ', dialCode: '+268' },
  { name: 'Ethiopia', code: 'ETH', dialCode: '+251' },
  { name: 'Fiji', code: 'FJI', dialCode: '+679' },
  { name: 'Finland', code: 'FIN', dialCode: '+358' },
  { name: 'France', code: 'FRA', dialCode: '+33' },
  { name: 'Gabon', code: 'GAB', dialCode: '+241' },
  { name: 'Gambia', code: 'GMB', dialCode: '+220' },
  { name: 'Georgia', code: 'GEO', dialCode: '+995' },
  { name: 'Germany', code: 'DEU', dialCode: '+49' },
  { name: 'Ghana', code: 'GHA', dialCode: '+233' },
  { name: 'Greece', code: 'GRC', dialCode: '+30' },
  { name: 'Grenada', code: 'GRD', dialCode: '+1-473' },
  { name: 'Guatemala', code: 'GTM', dialCode: '+502' },
  { name: 'Guinea', code: 'GIN', dialCode: '+224' },
  { name: 'Guinea-Bissau', code: 'GNB', dialCode: '+245' },
  { name: 'Guyana', code: 'GUY', dialCode: '+592' },
  { name: 'Haiti', code: 'HTI', dialCode: '+509' },
  { name: 'Honduras', code: 'HND', dialCode: '+504' },
  { name: 'Hungary', code: 'HUN', dialCode: '+36' },
  { name: 'Iceland', code: 'ISL', dialCode: '+354' },
  { name: 'India', code: 'IND', dialCode: '+91' },
  { name: 'Indonesia', code: 'IDN', dialCode: '+62' },
  { name: 'Iran', code: 'IRN', dialCode: '+98' },
  { name: 'Iraq', code: 'IRQ', dialCode: '+964' },
  { name: 'Ireland', code: 'IRL', dialCode: '+353' },
  { name: 'Israel', code: 'ISR', dialCode: '+972' },
  { name: 'Italy', code: 'ITA', dialCode: '+39' },
  { name: 'Jamaica', code: 'JAM', dialCode: '+1-876' },
  { name: 'Japan', code: 'JPN', dialCode: '+81' },
  { name: 'Jordan', code: 'JOR', dialCode: '+962' },
  { name: 'Kazakhstan', code: 'KAZ', dialCode: '+7' },
  { name: 'Kenya', code: 'KEN', dialCode: '+254' },
  { name: 'Kiribati', code: 'KIR', dialCode: '+686' },
  { name: 'Kuwait', code: 'KWT', dialCode: '+965' },
  { name: 'Kyrgyzstan', code: 'KGZ', dialCode: '+996' },
  { name: 'Laos', code: 'LAO', dialCode: '+856' },
  { name: 'Latvia', code: 'LVA', dialCode: '+371' },
  { name: 'Lebanon', code: 'LBN', dialCode: '+961' },
  { name: 'Lesotho', code: 'LSO', dialCode: '+266' },
  { name: 'Liberia', code: 'LBR', dialCode: '+231' },
  { name: 'Libya', code: 'LBY', dialCode: '+218' },
  { name: 'Liechtenstein', code: 'LIE', dialCode: '+423' },
  { name: 'Lithuania', code: 'LTU', dialCode: '+370' },
  { name: 'Luxembourg', code: 'LUX', dialCode: '+352' },
  { name: 'Madagascar', code: 'MDG', dialCode: '+261' },
  { name: 'Malawi', code: 'MWI', dialCode: '+265' },
  { name: 'Malaysia', code: 'MYS', dialCode: '+60' },
  { name: 'Maldives', code: 'MDV', dialCode: '+960' },
  { name: 'Mali', code: 'MLI', dialCode: '+223' },
  { name: 'Malta', code: 'MLT', dialCode: '+356' },
  { name: 'Marshall Islands', code: 'MHL', dialCode: '+692' },
  { name: 'Mauritania', code: 'MRT', dialCode: '+222' },
  { name: 'Mauritius', code: 'MUS', dialCode: '+230' },
  { name: 'Mexico', code: 'MEX', dialCode: '+52' },
  { name: 'Micronesia', code: 'FSM', dialCode: '+691' },
  { name: 'Moldova', code: 'MDA', dialCode: '+373' },
  { name: 'Monaco', code: 'MCO', dialCode: '+377' },
  { name: 'Mongolia', code: 'MNG', dialCode: '+976' },
  { name: 'Montenegro', code: 'MNE', dialCode: '+382' },
  { name: 'Morocco', code: 'MAR', dialCode: '+212' },
  { name: 'Mozambique', code: 'MOZ', dialCode: '+258' },
  { name: 'Myanmar', code: 'MMR', dialCode: '+95' },
  { name: 'Namibia', code: 'NAM', dialCode: '+264' },
  { name: 'Nauru', code: 'NRU', dialCode: '+674' },
  { name: 'Nepal', code: 'NPL', dialCode: '+977' },
  { name: 'Netherlands', code: 'NLD', dialCode: '+31' },
  { name: 'New Zealand', code: 'NZL', dialCode: '+64' },
  { name: 'Nicaragua', code: 'NIC', dialCode: '+505' },
  { name: 'Niger', code: 'NER', dialCode: '+227' },
  { name: 'Nigeria', code: 'NGA', dialCode: '+234' },
  { name: 'North Korea', code: 'PRK', dialCode: '+850' },
  { name: 'North Macedonia', code: 'MKD', dialCode: '+389' },
  { name: 'Norway', code: 'NOR', dialCode: '+47' },
  { name: 'Oman', code: 'OMN', dialCode: '+968' },
  { name: 'Pakistan', code: 'PAK', dialCode: '+92' },
  { name: 'Palau', code: 'PLW', dialCode: '+680' },
  { name: 'Palestine State', code: 'PSE', dialCode: '+970' },
  { name: 'Panama', code: 'PAN', dialCode: '+507' },
  { name: 'Papua New Guinea', code: 'PNG', dialCode: '+675' },
  { name: 'Paraguay', code: 'PRY', dialCode: '+595' },
  { name: 'Peru', code: 'PER', dialCode: '+51' },
  { name: 'Philippines', code: 'PHL', dialCode: '+63' },
  { name: 'Poland', code: 'POL', dialCode: '+48' },
  { name: 'Portugal', code: 'PRT', dialCode: '+351' },
  { name: 'Qatar', code: 'QAT', dialCode: '+974' },
  { name: 'Romania', code: 'ROU', dialCode: '+40' },
  { name: 'Russia', code: 'RUS', dialCode: '+7' },
  { name: 'Rwanda', code: 'RWA', dialCode: '+250' },
  { name: 'Saint Kitts and Nevis', code: 'KNA', dialCode: '+1-869' },
  { name: 'Saint Lucia', code: 'LCA', dialCode: '+1-758' },
  { name: 'Saint Vincent and the Grenadines', code: 'VCT', dialCode: '+1-784' },
  { name: 'Samoa', code: 'WSM', dialCode: '+685' },
  { name: 'San Marino', code: 'SMR', dialCode: '+378' },
  { name: 'Sao Tome and Principe', code: 'STP', dialCode: '+239' },
  { name: 'Saudi Arabia', code: 'SAU', dialCode: '+966' },
  { name: 'Senegal', code: 'SEN', dialCode: '+221' },
  { name: 'Serbia', code: 'SRB', dialCode: '+381' },
  { name: 'Seychelles', code: 'SYC', dialCode: '+248' },
  { name: 'Sierra Leone', code: 'SLE', dialCode: '+232' },
  { name: 'Singapore', code: 'SGP', dialCode: '+65' },
  { name: 'Slovakia', code: 'SVK', dialCode: '+421' },
  { name: 'Slovenia', code: 'SVN', dialCode: '+386' },
  { name: 'Solomon Islands', code: 'SLB', dialCode: '+677' },
  { name: 'Somalia', code: 'SOM', dialCode: '+252' },
  { name: 'South Africa', code: 'ZAF', dialCode: '+27' },
  { name: 'South Korea', code: 'KOR', dialCode: '+82' },
  { name: 'South Sudan', code: 'SSD', dialCode: '+211' },
  { name: 'Spain', code: 'ESP', dialCode: '+34' },
  { name: 'Sri Lanka', code: 'LKA', dialCode: '+94' },
  { name: 'Sudan', code: 'SDN', dialCode: '+249' },
  { name: 'Suriname', code: 'SUR', dialCode: '+597' },
  { name: 'Sweden', code: 'SWE', dialCode: '+46' },
  { name: 'Switzerland', code: 'CHE', dialCode: '+41' },
  { name: 'Syria', code: 'SYR', dialCode: '+963' },
  { name: 'Tajikistan', code: 'TJK', dialCode: '+992' },
  { name: 'Tanzania', code: 'TZA', dialCode: '+255' },
  { name: 'Thailand', code: 'THA', dialCode: '+66' },
  { name: 'Timor-Leste', code: 'TLS', dialCode: '+670' },
  { name: 'Togo', code: 'TGO', dialCode: '+228' },
  { name: 'Tonga', code: 'TON', dialCode: '+676' },
  { name: 'Trinidad and Tobago', code: 'TTO', dialCode: '+1-868' },
  { name: 'Tunisia', code: 'TUN', dialCode: '+216' },
  { name: 'Turkey', code: 'TUR', dialCode: '+90' },
  { name: 'Turkmenistan', code: 'TKM', dialCode: '+993' },
  { name: 'Tuvalu', code: 'TUV', dialCode: '+688' },
  { name: 'Uganda', code: 'UGA', dialCode: '+256' },
  { name: 'Ukraine', code: 'UKR', dialCode: '+380' },
  { name: 'United Arab Emirates', code: 'ARE', dialCode: '+971' },
  { name: 'United Kingdom', code: 'GBR', dialCode: '+44' },
  { name: 'United States', code: 'USA', dialCode: '+1' },
  { name: 'Uruguay', code: 'URY', dialCode: '+598' },
  { name: 'Uzbekistan', code: 'UZB', dialCode: '+998' },
  { name: 'Vanuatu', code: 'VUT', dialCode: '+678' },
  { name: 'Vatican City', code: 'VAT', dialCode: '+379' },
  { name: 'Venezuela', code: 'VEN', dialCode: '+58' },
  { name: 'Vietnam', code: 'VNM', dialCode: '+84' },
  { name: 'Yemen', code: 'YEM', dialCode: '+967' },
  { name: 'Zambia', code: 'ZMB', dialCode: '+260' },
  { name: 'Zimbabwe', code: 'ZWE', dialCode: '+263' }
];
